
import type { User, Job, LearningModule, Team } from '@/lib/types';

export const mockUser: User = {
  id: 'user-1',
  name: 'Savitri Bai',
  email: 'savitri.bai@example.com',
  avatarUrl: 'https://picsum.photos/seed/user1/100/100',
  skills: ['House Decoration', 'Plate Decoration for Function', 'Event Planning', 'Catering', 'Cooking'],
  experience: 'Over 5 years of experience in managing household functions, organizing community events, and providing high-quality catering services. Specializes in traditional and contemporary decor.',
  desiredJobType: 'Full-time',
  locationPreferences: 'Remote',
  industryPreferences: ['Hospitality', 'Events', 'Home Services'],
  rating: 4.5,
  membership: 'Rise',
  vasaPinkTokens: 250,
  mobileNumber: '9876543210',
  address: '123, Rose Garden Street, K.K. Nagar, Chennai, Tamil Nadu - 600078',
};

export const sampleJobs: Job[] = [
    {
      id: 'sample-job-1',
      title: 'Community Kitchen Chef',
      companyName: 'Community Help Group',
      companyLogoUrl: 'https://picsum.photos/seed/sample1/100/100',
      location: 'Chennai',
      jobType: 'Part-time',
      description: 'Looking for a chef to manage our community kitchen.',
      skillsRequired: ['Cooking', 'Menu Planning'],
      industry: 'Catering',
      status: 'Worker Assigned',
      date: '2024-08-16', // A Friday
      time: '10:00 AM - 4:00 PM',
    },
    {
      id: 'sample-job-2',
      title: 'Urgent Tailoring Work',
      companyName: 'Local Boutique',
      companyLogoUrl: 'https://picsum.photos/seed/sample2/100/100',
      location: 'Coimbatore',
      jobType: 'Contract',
      description: 'Need skilled tailors for a bulk order of dresses.',
      skillsRequired: ['Tailoring', 'Sewing'],
      industry: 'Fashion',
      status: 'Completed',
      date: '2024-08-10',
      time: '9:00 AM - 6:00 PM',
    },
    {
      id: 'sample-job-3',
      title: 'Farm Hand for Harvest',
      companyName: 'Green Fields Farm',
      companyLogoUrl: 'https://picsum.photos/seed/sample3/100/100',
      location: 'Salem',
      jobType: 'Contract',
      description: 'Seasonal work for harvesting crops.',
      skillsRequired: ['Farming', 'Harvesting'],
      industry: 'Agriculture',
      status: 'Worker Assigned',
      date: '2024-08-20',
      time: '7:00 AM - 3:00 PM',
    },
    {
      id: 'sample-job-4',
      title: 'Office Cleaning Staff',
      companyName: 'Corporate Solutions Ltd.',
      companyLogoUrl: 'https://picsum.photos/seed/sample4/100/100',
      location: 'Bangalore',
      jobType: 'Full-time',
      description: 'Daily cleaning and maintenance for our office premises.',
      skillsRequired: ['Cleaning', 'Sanitization'],
      industry: 'Domestic Services',
      status: 'Yet To Assign',
      date: '2024-09-01',
    },
    {
      id: 'sample-job-5',
      title: 'Event Catering Assistant',
      companyName: 'Grand Events',
      companyLogoUrl: 'https://picsum.photos/seed/sample5/100/100',
      location: 'Mumbai',
      jobType: 'Part-time',
      description: 'Assist in food preparation and serving for large events.',
      skillsRequired: ['Cooking', 'Catering', 'Serving'],
      industry: 'Events',
      status: 'Worker Assigned',
      date: '2024-08-18',
      time: '3:00 PM - 11:00 PM',
    },
     {
      id: 'sample-job-6',
      title: 'Wedding Planner Assistant',
      companyName: 'Dream Weddings',
      companyLogoUrl: 'https://picsum.photos/seed/sample6/100/100',
      location: 'Delhi',
      jobType: 'Internship',
      description: 'Assist the lead wedding planner in organizing and executing weddings. Excellent opportunity to learn.',
      skillsRequired: ['Event Planning', 'Communication', 'Organization'],
      industry: 'Events',
      status: 'Completed',
      date: '2024-08-05',
    },
    {
      id: 'sample-job-7',
      title: 'Home Baker for Festival',
      companyName: 'Sweet Delights',
      companyLogoUrl: 'https://picsum.photos/seed/sample7/100/100',
      location: 'Kolkata',
      jobType: 'Contract',
      description: 'Bulk order for traditional sweets and baked goods for the upcoming festival season.',
      skillsRequired: ['Baking', 'Cooking', 'Sweets Making'],
      industry: 'Catering',
      status: 'Worker Assigned',
      date: '2024-08-23', // Another Friday
      time: 'All Day',
    },
    {
      id: 'sample-job-8',
      title: 'House Cleaning Service',
      companyName: 'Self-employed',
      companyLogoUrl: 'https://picsum.photos/seed/sample8/100/100',
      location: 'Pune',
      jobType: 'Contract',
      description: 'Weekly house cleaning for a private residence.',
      skillsRequired: ['Cleaning', 'Housekeeping'],
      industry: 'Domestic Services',
      status: 'Worker Assigned',
      date: '2024-08-09', // A Friday
      time: '10:00 AM - 1:00 PM',
    },
    {
        id: 'sample-job-9',
        title: 'Gardening Maintenance',
        companyName: 'Green Spaces',
        companyLogoUrl: 'https://picsum.photos/seed/sample9/100/100',
        location: 'Chennai',
        jobType: 'Part-time',
        description: 'Regular maintenance for a residential garden.',
        skillsRequired: ['Gardening', 'Landscaping'],
        industry: 'Home Services',
        status: 'Worker Assigned',
        date: '2024-08-12',
        time: '9:00 AM - 12:00 PM',
    },
    {
        id: 'sample-job-10',
        title: 'Child Care for a Day',
        companyName: 'Private Request',
        companyLogoUrl: 'https://picsum.photos/seed/sample10/100/100',
        location: 'Bangalore',
        jobType: 'Contract',
        description: 'One-day child care for a 5-year-old.',
        skillsRequired: ['Child Care', 'First Aid'],
        industry: 'Child Care',
        status: 'Completed',
        date: '2024-08-12',
        time: 'Full Day',
    },
    {
        id: 'sample-job-11',
        title: 'Retail Store Help',
        companyName: 'City Mart',
        companyLogoUrl: 'https://picsum.photos/seed/sample11/100/100',
        location: 'Mumbai',
        jobType: 'Part-time',
        description: 'Assistance during peak hours at a busy retail store.',
        skillsRequired: ['Customer Service', 'Sales'],
        industry: 'Retail',
        status: 'Worker Assigned',
        date: '2024-08-17',
        time: '4:00 PM - 9:00 PM',
    },
    {
      id: 'sample-job-12',
      title: 'Festival Stall Setup',
      companyName: 'Community Events',
      companyLogoUrl: 'https://picsum.photos/seed/sample12/100/100',
      location: 'Chennai',
      jobType: 'Contract',
      description: 'Help set up stalls for the upcoming city festival.',
      skillsRequired: ['Manual Labor', 'Teamwork'],
      industry: 'Events',
      status: 'Worker Assigned',
      date: '2024-08-14',
      time: '8:00 AM - 5:00 PM',
    },
    {
      id: 'sample-job-13',
      title: 'Handicraft Workshop Assistant',
      companyName: 'Artisans Alliance',
      companyLogoUrl: 'https://picsum.photos/seed/sample13/100/100',
      location: 'Coimbatore',
      jobType: 'Part-time',
      description: 'Assist in conducting handicraft workshops for tourists.',
      skillsRequired: ['Handicrafts', 'Communication'],
      industry: 'Art & Craft',
      status: 'Completed',
      date: '2024-08-15',
      time: '11:00 AM - 3:00 PM',
    },
    {
      id: 'sample-job-14',
      title: 'Elderly Care Companion',
      companyName: 'Senior Care Services',
      companyLogoUrl: 'https://picsum.photos/seed/sample14/100/100',
      location: 'Bangalore',
      jobType: 'Part-time',
      description: 'Provide companionship and light assistance to an elderly person.',
      skillsRequired: ['Companionship', 'Patience'],
      industry: 'Healthcare',
      status: 'Worker Assigned',
      date: '2024-08-22',
      time: '10:00 AM - 2:00 PM',
    },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Head Chef',
    companyName: 'Gourmet Meals',
    companyLogoUrl: 'https://picsum.photos/seed/logo1/100/100',
    location: 'Mumbai, MH',
    jobType: 'Full-time',
    salary: '₹8,00,000 - ₹12,00,000 PA',
    description: 'Lead our kitchen team and create innovative menus. We are looking for a passionate chef with a flair for fusion cuisine.',
    skillsRequired: ['Culinary Arts', 'Menu Planning', 'Kitchen Management', 'Team Leadership'],
    industry: 'Hospitality',
  },
  {
    id: 'job-2',
    title: 'Master Potter',
    companyName: 'Earthly Vessels',
    companyLogoUrl: 'https://picsum.photos/seed/logo2/100/100',
    location: 'Jaipur, RJ',
    jobType: 'Full-time',
    salary: '₹4,00,000 - ₹6,00,000 PA',
    description: 'Join our artisan collective to craft beautiful pottery. Expertise in wheel-throwing and glazing techniques is required.',
    skillsRequired: ['Pottery', 'Wheel-throwing', 'Glazing', 'Ceramics'],
    industry: 'Art & Craft',
  },
  {
    id: 'job-3',
    title: 'House Cleaning Staff',
    companyName: 'Clean Homes Co.',
    companyLogoUrl: 'https://picsum.photos/seed/logo5/100/100',
    location: 'Pune, MH',
    jobType: 'Part-time',
    salary: '₹250 - ₹400 / hour',
    description: 'Reliable and detail-oriented staff needed for residential cleaning services. Flexible hours.',
    skillsRequired: ['Cleaning', 'Time Management', 'Hygiene Standards'],
    industry: 'Domestic Services',
  },
  {
    id: 'job-4',
    title: 'Babysitter / Nanny',
    companyName: 'Little Angels Care',
    companyLogoUrl: 'https://picsum.photos/seed/logo6/100/100',
    location: 'Delhi, NCR',
    jobType: 'Contract',
    salary: '₹300 - ₹500 / hour',
    description: 'Caring and responsible babysitter required for a family with two young children. Experience with toddlers is a must.',
    skillsRequired: ['Child Care', 'First Aid', 'Patience', 'Communication'],
    industry: 'Child Care',
  },
   {
    id: 'job-5',
    title: 'Home Nurse',
    companyName: 'Health at Home',
    companyLogoUrl: 'https://picsum.photos/seed/logo7/100/100',
    location: 'Bangalore, KA',
    jobType: 'Full-time',
    salary: '₹25,000 - ₹40,000 / month',
    description: 'Certified home nurse to provide compassionate care for elderly patients. Duties include monitoring vitals, administering medication, and personal care.',
    skillsRequired: ['Nursing', 'Patient Care', 'Medication Administration', 'Empathy'],
    industry: 'Healthcare',
  },
  {
    id: 'job-6',
    title: 'Tailoring and Alterations Specialist',
    companyName: "Stree Shakti Styles",
    companyLogoUrl: 'https://picsum.photos/seed/logo8/100/100',
    location: 'Chennai, TN',
    jobType: 'Part-time',
    salary: '₹15,000 - ₹20,000 / month',
    description: 'Skilled tailor needed for custom clothing and alterations. Must be proficient with various fabrics and sewing machines.',
    skillsRequired: ['Tailoring', 'Sewing', 'Pattern Making', 'Alterations'],
    industry: 'Fashion',
  },
  {
    id: 'job-7',
    title: 'Event Decorator',
    companyName: "Mahila Mandan Events",
    companyLogoUrl: 'https://picsum.photos/seed/logo9/100/100',
    location: 'Kolkata, WB',
    jobType: 'Contract',
    salary: 'Project-based',
    description: 'Creative and organized event decorator for weddings and corporate events. Strong portfolio required.',
    skillsRequired: ['Event Decoration', 'Floral Arrangement', 'Client Communication', 'Budgeting'],
    industry: 'Events',
  },
  {
    id: 'job-8',
    title: 'Organic Farm Manager',
    companyName: "Nari Khet Organics",
    companyLogoUrl: 'https://picsum.photos/seed/logo10/100/100',
    location: 'Rural Punjab',
    jobType: 'Full-time',
    salary: '₹30,000 / month + accommodation',
    description: 'Manage a small organic farm, overseeing crop cultivation, harvesting, and local sales. Passion for sustainable agriculture is key.',
    skillsRequired: ['Farming', 'Organic Practices', 'Crop Management', 'Sales'],
    industry: 'Agriculture',
  },
];


export const mockLearningModules: LearningModule[] = [
  {
    id: 'learn-1-en',
    title: 'Professional Cooking Techniques',
    description: 'Master the fundamental techniques of professional cooking, from knife skills to sauce making.',
    type: 'video',
    duration: '10 min',
    imageUrl: 'https://picsum.photos/seed/cook/600/400',
    progress: 40,
    language: 'en',
    videoId: '1tVUj2g5A2s'
  },
  {
    id: 'learn-1-hi',
    title: 'Professional Cooking Techniques (Hindi)',
    description: 'Master the fundamental techniques of professional cooking, from knife skills to sauce making, in Hindi.',
    type: 'video',
    duration: '13 min',
    imageUrl: 'https://picsum.photos/seed/cook2/600/400',
    progress: 20,
    language: 'hi',
    videoId: 'Gup8L4s-gPA'
  },
  {
    id: 'learn-2-en',
    title: 'Advanced Digital Marketing',
    description: 'Learn SEO, SEM, and social media strategies to boost your online presence.',
    type: 'video',
    duration: '10 min',
    imageUrl: 'https://picsum.photos/seed/marketing/600/400',
    progress: 0,
    language: 'en',
    videoId: 'sO4-24r_ioU'
  },
    {
    id: 'learn-2-hi',
    title: 'Advanced Digital Marketing (Hindi)',
    description: 'Learn SEO, SEM, and social media strategies to boost your online presence, in Hindi.',
    type: 'video',
    duration: '15 min',
    imageUrl: 'https://picsum.photos/seed/marketing2/600/400',
    progress: 0,
    language: 'hi',
    videoId: '52hR-dJM3M0'
  },
  {
    id: 'learn-3-en',
    title: 'The Art of Plate Decoration',
    description: 'Learn how to present your culinary creations with artistic flair and elegance.',
    type: 'video',
    duration: '8 min',
    imageUrl: 'https://picsum.photos/seed/plate/600/400',
    progress: 75,
    language: 'en',
    videoId: 'i8aY2a7V2z0'
  },
   {
    id: 'learn-3-hi',
    title: 'The Art of Plate Decoration (Hindi)',
    description: 'Learn how to present your culinary creations with artistic flair and elegance, in Hindi.',
    type: 'video',
    duration: '4 min',
    imageUrl: 'https://picsum.photos/seed/plate2/600/400',
    progress: 10,
    language: 'hi',
    videoId: 'k-y_s4qises'
  },
  {
    id: 'learn-4-hi',
    title: 'Introduction to Coding with Python (Hindi)',
    description: 'A beginner-friendly introduction to the world of programming with Python, in Hindi.',
    type: 'video',
    duration: '1 hour',
    imageUrl: 'https://picsum.photos/seed/coding2/600/400',
    progress: 5,
    language: 'hi',
    videoId: 'v5-rF_63-v0'
  },
  {
    id: 'learn-5-ta',
    title: 'Introduction to Python (Tamil)',
    description: 'A beginner-friendly introduction to Python programming in Tamil.',
    type: 'video',
    duration: '30 min',
    imageUrl: 'https://picsum.photos/seed/coding3/600/400',
    progress: 0,
    language: 'ta',
    videoId: 'ASrD2-iC0gY'
  },
  {
    id: 'learn-6-en',
    title: 'Start a Home Salon & Spa',
    description: 'Learn how to start your own salon and spa business from home, covering services like facials, waxing, and threading.',
    type: 'video',
    duration: '8 min',
    imageUrl: 'https://picsum.photos/seed/salon/600/400',
    progress: 0,
    language: 'en',
    videoId: 'YV2p_23s1xE'
  }
];

export const mockTeams: Team[] = [
  {
    id: 'team-1',
    name: 'Sakthi Women Catering',
    description: 'A collective of talented home chefs providing catering for local events and functions.',
    members: [
      { id: 'user-1', name: 'Savitri Bai', avatarUrl: 'https://picsum.photos/seed/user1/100/100' },
      { id: 'user-2', name: 'Priya Kaur', avatarUrl: 'https://picsum.photos/seed/user2/100/100' },
      { id: 'user-3', name: 'Aisha Begum', avatarUrl: 'https://picsum.photos/seed/user3/100/100' },
    ],
  },
  {
    id: 'team-2',
    name: 'Pengal Farm Working & Co',
    description: 'A team dedicated to organic farming, and selling fresh produce at local markets.',
    members: [
      { id: 'user-1', name: 'Savitri Bai', avatarUrl: 'https://picsum.photos/seed/user1/100/100' },
    ],
  },
  {
    id: 'team-3',
    name: 'Kalaiveena Artisans',
    description: 'A group for women artisans to collaborate on projects, share techniques, and sell handmade crafts.',
    members: [
      { id: 'user-4', name: 'Meena Kumari', avatarUrl: 'https://picsum.photos/seed/user4/100/100' },
      { id: 'user-5', name: 'Lakshmi Devi', avatarUrl: 'https://picsum.photos/seed/user5/100/100' },
    ],
  },
  {
    id: 'team-4',
    name: 'Chennai ChildMinders',
    description: 'A reliable network of experienced nannies and babysitters in the Chennai area.',
    members: [
      { id: 'user-6', name: 'Geeta', avatarUrl: 'https://picsum.photos/seed/user6/100/100' },
      { id: 'user-7', name: 'Sunita', avatarUrl: 'https://picsum.photos/seed/user7/100/100' },
    ],
  },
  {
    id: 'team-5',
    name: 'Bangalore Bakers Collective',
    description: 'Passionate bakers creating custom cakes and pastries for all occasions.',
    members: [
       { id: 'user-8', name: 'Anjali', avatarUrl: 'https://picsum.photos/seed/user8/100/100' },
       { id: 'user-9', name: 'Pooja', avatarUrl: 'https://picsum.photos/seed/user9/100/100' },
    ],
  },
    {
    id: 'team-6',
    name: 'Jaipur HandiCrafts',
    description: 'A team of artisans creating and selling traditional Jaipuri textiles and crafts.',
    members: [
        { id: 'user-10', name: 'Rani', avatarUrl: 'https://picsum.photos/seed/user10/100/100' },
    ],
  },
];

export const mockWorkerHistory = [
    { id: 'wh-1', title: 'Urgent Tailoring Work', dateCompleted: '2024-08-10', amountEarned: 12000 },
    { id: 'wh-2', title: 'Community Kitchen Chef', dateCompleted: '2024-08-01', amountEarned: 8000 },
    { id: 'wh-3', title: 'Organic Farm Hand', dateCompleted: '2024-07-15', amountEarned: 6500 },
];

export const mockRecruiterHistory = [
    { id: 'rh-1', title: 'Wedding Planner Assistant', workersHired: ['Lakshmi P.', 'Sunita D.'], amountPaid: 15000, pointsEarned: 150 },
    { id: 'rh-2', title: 'Home Baker for Festival', workersHired: ['Anjali S.'], amountPaid: 7500, pointsEarned: 75 },
];


export const workerMonetizationData = {
  monthly: [
    { label: 'Jan', amount: 8500, jobs: 3 },
    { label: 'Feb', amount: 7200, jobs: 2 },
    { label: 'Mar', amount: 9800, jobs: 4 },
    { label: 'Apr', amount: 6500, jobs: 2 },
    { label: 'May', amount: 11000, jobs: 5 },
    { label: 'Jun', amount: 9200, jobs: 3 },
  ],
  weekly: [
    { label: 'W1', amount: 2200, jobs: 1 },
    { label: 'W2', amount: 1800, jobs: 1 },
    { label: 'W3', amount: 3500, jobs: 2 },
    { label: 'W4', amount: 1700, jobs: 1 },
  ],
  last_10_days: [
    { label: 'Day 1', amount: 0, jobs: 0 },
    { label: 'Day 2', amount: 500, jobs: 1 },
    { label: 'Day 3', amount: 0, jobs: 0 },
    { label: 'Day 4', amount: 800, jobs: 1 },
    { label: 'Day 5', amount: 0, jobs: 0 },
    { label: 'Day 6', amount: 1200, jobs: 1 },
    { label: 'Day 7', amount: 0, jobs: 0 },
    { label: 'Day 8', amount: 0, jobs: 0 },
    { label: 'Day 9', amount: 750, jobs: 1 },
    { label: 'Day 10', amount: 0, jobs: 0 },
  ],
};

export const recruiterMonetizationData = {
  monthly: [
    { label: 'Jan', amount: 15000, commission: 750, workers: 5 },
    { label: 'Feb', amount: 12000, commission: 600, workers: 4 },
    { label: 'Mar', amount: 20000, commission: 1000, workers: 8 },
    { label: 'Apr', amount: 18000, commission: 900, workers: 6 },
    { label: 'May', amount: 25000, commission: 1250, workers: 10 },
    { label: 'Jun', amount: 22000, commission: 1100, workers: 9 },
  ],
  weekly: [
    { label: 'W1', amount: 5000, commission: 250, workers: 2 },
    { label: 'W2', amount: 4000, commission: 200, workers: 2 },
    { label: 'W3', amount: 7000, commission: 350, workers: 3 },
    { label: 'W4', amount: 6000, commission: 300, workers: 2 },
  ],
  last_10_days: [
    { label: 'Day 1', amount: 0, commission: 0, workers: 0 },
    { label: 'Day 2', amount: 1500, commission: 75, workers: 1 },
    { label: 'Day 3', amount: 2000, commission: 100, workers: 2 },
    { label: 'Day 4', amount: 0, commission: 0, workers: 0 },
    { label: 'Day 5', amount: 3000, commission: 150, workers: 2 },
    { label: 'Day 6', amount: 0, commission: 0, workers: 0 },
    { label: 'Day 7', amount: 2500, commission: 125, workers: 1 },
    { label: 'Day 8', amount: 0, commission: 0, workers: 0 },
    { label: 'Day 9', amount: 1000, commission: 50, workers: 1 },
    { label: 'Day 10', amount: 4000, commission: 200, workers: 3 },
  ],
};
