// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
'use client';

import { useState, useEffect, useMemo } from 'react';
import {
  onSnapshot,
  collection,
  query,
  where,
  orderBy,
  limit,
  QueryConstraint,
  CollectionReference,
} from 'firebase/firestore';
import { useFirestore } from '../provider';

interface QueryOptions {
  where?: [string, '==', any];
  orderBy?: [string, 'asc' | 'desc'];
  limit?: number;
}

export function useCollection<T>(path: string, opts?: QueryOptions) {
  const db = useFirestore();
  const [data, setData] = useState<T[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const collectionRef = useMemo(
    () => (db ? collection(db, path) : null),
    [db, path]
  );

  const queryConstraints = useMemo(() => {
    const constraints: QueryConstraint[] = [];
    if (opts?.where) constraints.push(where(...opts.where));
    if (opts?.orderBy) constraints.push(orderBy(...opts.orderBy));
    if (opts?.limit) constraints.push(limit(opts.limit));
    return constraints;
  }, [opts?.where, opts?.orderBy, opts?.limit]);

  useEffect(() => {
    if (!collectionRef) {
      setLoading(false);
      return;
    }

    const q = query(collectionRef, ...queryConstraints);

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        const result: T[] = [];
        snapshot.forEach((doc) => {
          result.push({ id: doc.id, ...doc.data() } as T);
        });
        setData(result);
        setLoading(false);
      },
      (err) => {
        console.error(err);
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [collectionRef, queryConstraints]);

  return { data, loading, error };
}
