// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
'use client';

import { FirebaseProvider, type FirebaseContextValue } from './provider';
import { initializeFirebase } from '.';

let firebase: FirebaseContextValue;

export function FirebaseClientProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  if (!firebase) {
    firebase = initializeFirebase();
  }
  return <FirebaseProvider {...firebase}>{children}</FirebaseProvider>;
}
