// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

import { initializeApp, getApp, getApps, type FirebaseOptions } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth } from 'firebase/auth';

const firebaseConfig = {
  apiKey: "AIzaSyClKKrYHgGnW2ltvrXPd5mTrwVVrcEdvkE",
  authDomain: "studio-9096752878-3dca9.firebaseapp.com",
  projectId: "studio-9096752878-3dca9",
  storageBucket: "studio-9096752878-3dca9.firebasestorage.app",
  messagingSenderId: "780954864730",
  appId: "1:780954864730:web:5cb3158728adf02b8bdc63"
};

// Initialize Firebase
export const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
export const db = getFirestore(app);
export const auth = getAuth(app);
