// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
'use client';

import { createContext, useContext, useMemo } from 'react';
import type { FirebaseApp } from 'firebase/app';
import type { Auth } from 'firebase/auth';
import type { Firestore } from 'firebase/firestore';

export interface FirebaseContextValue {
  firebaseApp: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
}

const FirebaseContext = createContext<FirebaseContextValue | undefined>(
  undefined
);

export interface FirebaseProviderProps extends FirebaseContextValue {
  children: React.ReactNode;
}

export function FirebaseProvider({
  children,
  ...value
}: FirebaseProviderProps) {
  const memoizedValue = useMemo(
    () => ({
      firebaseApp: value.firebaseApp,
      auth: value.auth,
      firestore: value.firestore,
    }),
    [value.firebaseApp, value.auth, value.firestore]
  );
  return (
    <FirebaseContext.Provider value={memoizedValue}>
      {children}
    </FirebaseContext.Provider>
  );
}

export function useFirebase() {
  const context = useContext(FirebaseContext);
  if (context === undefined) {
    throw new Error('useFirebase must be used within a FirebaseProvider');
  }
  return context;
}

export function useFirebaseApp() {
  const { firebaseApp } = useFirebase();
  return firebaseApp;
}

export function useAuth() {
  const { auth } = useFirebase();
  return auth;
}

export function useFirestore() {
  const { firestore } = useFirebase();
  return firestore;
}
